<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GitHubReleaseUpdater.Cli</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GitHubReleaseUpdater\GitHubReleaseUpdater.csproj" />
  </ItemGroup>

</Project>
